// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/transfer.proto

package grpc_file_transfer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferServiceClient interface {
	GetBatchTransfer(ctx context.Context, in *TransferInfoMsg, opts ...grpc.CallOption) (*GetBatchTransferMsg, error)
	PutBatchTransfer(ctx context.Context, in *PutBatchTransferMsg, opts ...grpc.CallOption) (*TransferInfoMsg, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) GetBatchTransfer(ctx context.Context, in *TransferInfoMsg, opts ...grpc.CallOption) (*GetBatchTransferMsg, error) {
	out := new(GetBatchTransferMsg)
	err := c.cc.Invoke(ctx, "/proto.TransferService/GetBatchTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) PutBatchTransfer(ctx context.Context, in *PutBatchTransferMsg, opts ...grpc.CallOption) (*TransferInfoMsg, error) {
	out := new(TransferInfoMsg)
	err := c.cc.Invoke(ctx, "/proto.TransferService/PutBatchTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations must embed UnimplementedTransferServiceServer
// for forward compatibility
type TransferServiceServer interface {
	GetBatchTransfer(context.Context, *TransferInfoMsg) (*GetBatchTransferMsg, error)
	PutBatchTransfer(context.Context, *PutBatchTransferMsg) (*TransferInfoMsg, error)
	mustEmbedUnimplementedTransferServiceServer()
}

// UnimplementedTransferServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransferServiceServer struct {
}

func (UnimplementedTransferServiceServer) GetBatchTransfer(context.Context, *TransferInfoMsg) (*GetBatchTransferMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatchTransfer not implemented")
}
func (UnimplementedTransferServiceServer) PutBatchTransfer(context.Context, *PutBatchTransferMsg) (*TransferInfoMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutBatchTransfer not implemented")
}
func (UnimplementedTransferServiceServer) mustEmbedUnimplementedTransferServiceServer() {}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_GetBatchTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferInfoMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetBatchTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TransferService/GetBatchTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetBatchTransfer(ctx, req.(*TransferInfoMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_PutBatchTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBatchTransferMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).PutBatchTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TransferService/PutBatchTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).PutBatchTransfer(ctx, req.(*PutBatchTransferMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBatchTransfer",
			Handler:    _TransferService_GetBatchTransfer_Handler,
		},
		{
			MethodName: "PutBatchTransfer",
			Handler:    _TransferService_PutBatchTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transfer.proto",
}
